export default [
	{
		employer_name: "Maddisoft",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "ZipRecruiter",
		job_id: "Tdnx0euC4QcAAAAAAAAAAA==",
		job_employment_type: "CONTRACTOR",
		job_title: "Python Developer",
		job_apply_link:
			"https://www.ziprecruiter.com/c/Maddisoft/Job/Python-Developer/-in-Houston,TX?jid=9dc4137e669a5ca2",
		job_apply_is_direct: true,
		job_apply_quality_score: 0.716,
		job_description:
			"Maddisoft has the following immediate opportunity, let us know if you or someone you know would be interested. Send in your resume ASAP. - U.S. Citizens and those authorized to work in the U.S. are encouraged to apply. Looking for W2 CONTRACT, Send in resume along with LinkedIn profile without which applications will not be considered. Call us NOW! ***Visa sponsorship is available for this position.***\nRole: Python Developer\nLocation: Houston Texas\nDuration: 12+ months with possible extension\nJob Description\nOur Client to apply advanced analytics and modeling to address challenging business problems. They are looking for a Python Developer to join their Enterprise Data and Analytics team to help them built and maintain data pipelines and data science models. the Consultant will be responsible for developing solutions within the Azure DevOps Platform that will be deployed on AWS Databricks. The successful candidate will be a self-starter who is comfortable working in a fast-paced environment and has a passion for learning new technologies. Knowledge of Spark, Delta Lake, Agile methodology and the energy industry is a plus.\n• Develop and maintain data pipelines and data science models using Python\n• Work with business users to understand requirements and translate them into technical solutions\n• Work with data scientists to productionize their models\n• Work with data engineers to ensure data quality and consistency\n• Follow Agile methodology and Software Engineering best practices\nQualifications:\n• Bachelor's degree in Computer Science, Engineering, or related field\n• 5+ years of experience in Python development\n• Working knowledge of Software Engineering best practices: unit testing, code reviews, design documentation, etc.\n• Good communication skills\n• Experience with Git, Pandas, PySpark, and SQL",
		job_is_remote: false,
		job_posted_at_timestamp: 1687488112,
		job_posted_at_datetime_utc: "2023-06-23T02:41:52.000Z",
		job_city: "Houston",
		job_state: "TX",
		job_country: "US",
		job_latitude: 29.760427,
		job_longitude: -95.369804,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Tdnx0euC4QcAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-07-24T00:00:00.000Z",
		job_offer_expiration_timestamp: 1690156800,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 60,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"They are looking for a Python Developer to join their Enterprise Data and Analytics team to help them built and maintain data pipelines and data science models",
				"The successful candidate will be a self-starter who is comfortable working in a fast-paced environment and has a passion for learning new technologies",
				"Bachelor's degree in Computer Science, Engineering, or related field",
				"5+ years of experience in Python development",
				"Working knowledge of Software Engineering best practices: unit testing, code reviews, design documentation, etc",
				"Good communication skills",
				"Experience with Git, Pandas, PySpark, and SQL",
			],
			Responsibilities: [
				"Our Client to apply advanced analytics and modeling to address challenging business problems",
				"the Consultant will be responsible for developing solutions within the Azure DevOps Platform that will be deployed on AWS Databricks",
				"Develop and maintain data pipelines and data science models using Python",
				"Work with business users to understand requirements and translate them into technical solutions",
				"Work with data scientists to productionize their models",
				"Work with data engineers to ensure data quality and consistency",
				"Follow Agile methodology and Software Engineering best practices",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"15-1132.00: Software Developers, Applications",
		],
	},
	{
		employer_name: "Saxon Global",
		employer_logo:
			"https://linkedin-companies-logos.s3.amazonaws.com/saxonglobal_66",
		employer_website: "http://www.saxonglobal.com",
		employer_company_type: null,
		job_publisher: "Learn4Good",
		job_id: "CMZW4FyawOoAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Python Developer",
		job_apply_link:
			"https://www.learn4good.com/jobs/texas/info_technology/2419377641/e/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.4023,
		job_description:
			"Location: Westlake\nThe Expertise and Skills You Bring\n\n• Hands-on experience in 2 or more languages (Python, Java, Go etc.).\n\n• Hands-on experience designing and building scalable and resilient applications in the cloud.\n\n• Serverless hands-on development and architecture experience implementing Lambda, API Gateway, Step Functions, etc\n\n• Experience delivering software using engineering best practices and principles.\n\n• Extensive knowledge of infrastructure as code (Terraform, CFT, CDK, etc.).\n\n• Hands-on experience with continuous integration and continuous delivery/deployment.\n\n• Passion for new technologies and cloud trends.\nBonus skills\n\n• Cloud Certifications in AWS.\n\n• Hands on experience with any of the following, Data Dog, Splunk, Prometheus, etc for Observability Tools.\n\n• Experience working across multiple cross functional teams.",
		job_is_remote: false,
		job_posted_at_timestamp: 1687564800,
		job_posted_at_datetime_utc: "2023-06-24T00:00:00.000Z",
		job_city: "Westlake",
		job_state: "TX",
		job_country: "US",
		job_latitude: 32.991234,
		job_longitude: -97.195015,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=CMZW4FyawOoAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-12-23T00:00:00.000Z",
		job_offer_expiration_timestamp: 1703289600,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: true,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"Hands-on experience in 2 or more languages (Python, Java, Go etc.)",
				"Hands-on experience designing and building scalable and resilient applications in the cloud",
				"Serverless hands-on development and architecture experience implementing Lambda, API Gateway, Step Functions, etc",
				"Experience delivering software using engineering best practices and principles",
				"Extensive knowledge of infrastructure as code (Terraform, CFT, CDK, etc.)",
				"Hands-on experience with continuous integration and continuous delivery/deployment",
				"Passion for new technologies and cloud trends",
				"Cloud Certifications in AWS",
				"Hands on experience with any of the following, Data Dog, Splunk, Prometheus, etc for Observability Tools",
				"Experience working across multiple cross functional teams",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"Python",
			"Cloud",
			"Software Engineer",
			"AWS",
		],
	},
	{
		employer_name: "TensorIoT Inc.",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Learn4Good",
		job_id: "6JPTie9w2RkAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Python Developer - Remote",
		job_apply_link:
			"https://www.learn4good.com/jobs/online_remote/info_technology/2420256994/e/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.3957,
		job_description:
			"Job Description\n\nAccepting remote candidates in the following states:\nArizona, California, Colorado, Delaware, Florida, Maryland, Minnesota, North Carolina, Nevada, Texas, Virginia, Washington, and Wisconsin. Tensor\n\nIoT is seeking a Mid-Senior Level Python Developer to become an integral part of our team! Leveraging the AWS (Amazon Web Services) platform we work to build new and unique solutions in the smart devices vertical across many different industry sectors. We're looking for tech-savvy enthusiasts with a passion for IoT (Internet of Things) and or ML/AI (Machine Learning/Artificial Intelligence). Apply today and join our team!\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n• Collaborate with external clients and internal team members to meet product deadlines\n\nQualifications:\n• BS in Computer Science, Engineering or Related Fields\n• 3+ years of previous experience in software development, computer engineering, or other related fields\n• Strong experience with Python, Node.\n\nJS, TypeScript, AWS, and GraphQL\n• Familiarity and comfort with REST APIs Preferred (Not Required):\n• IoT/ML/AI/VR Experience\n• Experience with Black Duck, Sonar, Circle Cl, Zephyr Company Description Tensor\n\nIoT's founders helped build world-class IoT and AI platforms at AWS, and Google and are now creating solutions to simplify the way enterprises incorporate edge devices and their data into their day to day operations. Our mission is to help connect devices and make them smarter. Our founders firmly believe in the transformative potential of smarter devices to enhance our quality of life and we're just getting started!\n\nConnect with us today to learn more!\n\nCompany Description\n\nTensor\n\nIoT's founders helped build world-class IoT and AI platforms at AWS, and Google and are now creating solutions to simplify the way enterprises incorporate edge devices and their data into their day to day operations. Our mission is to help connect devices and make them smarter. Our founders firmly believe in the transformative potential of smarter devices to enhance our quality of life and we're just getting started!\n\nConnect with us today to learn more!",
		job_is_remote: true,
		job_posted_at_timestamp: 1687564800,
		job_posted_at_datetime_utc: "2023-06-24T00:00:00.000Z",
		job_city: "Houston",
		job_state: "TX",
		job_country: "US",
		job_latitude: 29.760427,
		job_longitude: -95.369804,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=6JPTie9w2RkAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-12-23T00:00:00.000Z",
		job_offer_expiration_timestamp: 1703289600,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 36,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"BS in Computer Science, Engineering or Related Fields",
				"3+ years of previous experience in software development, computer engineering, or other related fields",
				"Strong experience with Python, Node",
				"JS, TypeScript, AWS, and GraphQL",
				"IoT/ML/AI/VR Experience",
				"Experience with Black Duck, Sonar, Circle Cl, Zephyr Company Description Tensor",
			],
			Responsibilities: [
				"Analyze user needs and develop software solutions",
				"Work with project manager or product owner to meet specification needs",
				"Recommend software upgrades to optimize operational efficiency",
				"Collaborate with other developers to design and optimize code",
				"Create flowcharts and user guides for new and existing programs",
				"Document all programming tasks and procedures",
				"Perform routine software maintenance",
				"Collaborate with external clients and internal team members to meet product deadlines",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"Senior Developer",
			"Software Engineer",
			"Python",
			"Javascript",
		],
	},
	{
		employer_name: "Motion Recruitment",
		employer_logo:
			"https://media.licdn.com/dms/image/C4E0BAQGbIGAVD9Ugtg/company-logo_200_200/0/1571148939283?e=2147483647&v=beta&t=ruWLGWrzbxhqHFb8RNpKYfWqXlatRigK3VpMylXublI",
		employer_website: "http://motionrecruitment.com",
		employer_company_type: "Staffing",
		job_publisher: "Learn4Good",
		job_id: "uTOG7wd7NPoAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Python Developer​/Python, C++",
		job_apply_link:
			"https://www.learn4good.com/jobs/dallas/texas/info_technology/2420516073/e/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.3928,
		job_description:
			"Position: Python Developer (Python, C++)\nJob Description This premier entertainment and technology-driven sports venue that combines golf, competition, and interactive experiences is looking for a dedicated Python Developer. This company has revolutionized the golfing experience and become a global leader in sports entertainment with their unique blend of technology, entertainment, and hospitality. Be part of a team that is passionate about pushing boundaries and creating memorable experiences, your contributions will directly impact the millions of guests worldwide.\n\nThis company leverages the latest technologies to create an immersive experience for their guests where you will have the chance to work with state-of-the-art technology and stay at the forefront of the industry. Join this company to enjoy a positive work environment, team-building activities, and opportunities to engage with colleagues who share a passion for technology and entertainment. As a Python Engineer your day-to-day will include developing an application that enhances the gameplay experience for users by utilizing your expertise in Python and C++.\n\nThis application could involve real-time data processing, interactive game features, and seamless integration with their venue technology systems. Additionally, you will design, develop, and implement backend systems, APIs, and services to support various aspects of the gaming experience. Get ready to exercise your excellent communication and collaboration skills to work effectively with the innovative cross-functional teams. Take your career to new heights as a Python Developer at this global sports venue!\n\nContract Duration: 12 Months Required Skills & Experience\n\n• Python\n\n• C++\n\n• Plotly, Num Py\n\n• CAD (Creo, NX)\n\n• 3D Modeling\nDesired Skills & Experience\n\n• Visual Studio\n\n• Java Script\n\n• REST APIs\n\n• Git, Git Hub\n\n• HTML/CSS\nWhat You Will Be Doing Tech Breakdown\n\n• 100% Python, C++\nDaily\n\nResponsibilities\n\n• 80% Hands On\n\n• 20% Team Collaboration\n\nYou will receive the following benefits:\n\n• Medical Insurance - Four medical plans to choose from for you and your family\n\n• Dental & Orthodontia Benefits\n\n• Vision Benefits\n\n• Health Savings Account (HSA)\n\n• Health and Dependent Care Flexible Spending Accounts\n\n• Voluntary Life Insurance, Long-Term & Short-Term Disability Insurance\n\n• Hospital Indemnity Insurance\n\n• 401(k) including match with pre and post-tax options\n\n• Paid Sick Time Leave\n\n• Legal and Identity Protection Plans\n\n• Pre-tax Commuter Benefit\n\n• 529 College Saver Plan\n\nMotion Recruitment Partners is an Equal Opportunity Employer, including Veterans/Disability/Women. All applicants must be currently authorized to work on a full-time basis in the country for which they are applying, and no sponsorship is currently available. Accommodation will be provided in all parts of the hiring process as required under Motion Recruitment Employment Accommodation policy. Applicants need to make their needs known in advance.\n\nPosted by:\nClaudia January",
		job_is_remote: false,
		job_posted_at_timestamp: 1687651200,
		job_posted_at_datetime_utc: "2023-06-25T00:00:00.000Z",
		job_city: "Dallas",
		job_state: "TX",
		job_country: "US",
		job_latitude: 32.776665,
		job_longitude: -96.79699,
		job_benefits: ["paid_time_off", "retirement_savings", "health_insurance"],
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=uTOG7wd7NPoAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-12-24T00:00:00.000Z",
		job_offer_expiration_timestamp: 1703376000,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 12,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"Contract Duration: 12 Months Required Skills & Experience",
				"Python",
				"C++",
				"CAD (Creo, NX)",
				"3D Modeling",
			],
			Responsibilities: [
				"As a Python Engineer your day-to-day will include developing an application that enhances the gameplay experience for users by utilizing your expertise in Python and C++",
				"This application could involve real-time data processing, interactive game features, and seamless integration with their venue technology systems",
				"Additionally, you will design, develop, and implement backend systems, APIs, and services to support various aspects of the gaming experience",
				"Get ready to exercise your excellent communication and collaboration skills to work effectively with the innovative cross-functional teams",
				"What You Will Be Doing Tech Breakdown",
				"100% Python, C++",
				"80% Hands On",
				"20% Team Collaboration",
			],
			Benefits: [
				"Medical Insurance - Four medical plans to choose from for you and your family",
				"Dental & Orthodontia Benefits",
				"Vision Benefits",
				"Health Savings Account (HSA)",
				"Health and Dependent Care Flexible Spending Accounts",
				"Voluntary Life Insurance, Long-Term & Short-Term Disability Insurance",
				"Hospital Indemnity Insurance",
				"401(k) including match with pre and post-tax options",
				"Paid Sick Time Leave",
				"Legal and Identity Protection Plans",
				"Pre-tax Commuter Benefit",
				"529 College Saver Plan",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"Software Engineer",
			"Python",
			"Tech",
			"Systems Developer",
		],
		job_naics_code: "561311",
		job_naics_name: "Employment Placement Agencies",
	},
	{
		employer_name: "Patterned Learning AI",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "ZipRecruiter",
		job_id: "I1mL8GW4cggAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Junior Python Developer-US/Canada",
		job_apply_link:
			"https://www.ziprecruiter.com/c/Patterned-Learning-AI/Job/Junior-Python-Developer-US-Canada/-in-Houston,TX?jid=1c72a6a406337dcc",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.6777,
		job_description:
			"REMOTE (US/Canada Residing people only, with work permit) Patterned Learning - Junior Python Developer-US/Canada , FULL-TIME, Salary $70K - $80K a year.\n\nAbout us: The Future of AI is Patterned, a stealth-mode technology startup. Top investors include Sequoia and Anderson Horowitz, founders from Google, DeepMind, and NASA and we're hiring for almost everything!\n\nJob Description:\n\nWe are seeking a talented and motivated Junior Python Developer to join our dynamic team. In this role, you will work closely with senior developers and other cross-functional teams to develop and maintain high-quality Python applications. As a Junior Python Developer, you will have the opportunity to learn and grow your skills while contributing to exciting projects.\n\nResponsibilities:\n• Collaborate with senior developers to design and develop Python applications.\n• Write clean, efficient, and maintainable code that follows best practices.\n• Participate in code reviews and provide constructive feedback.\n• Debug and fix issues in existing codebase.\n• Assist in testing and quality assurance processes.\n• Stay updated with the latest trends and technologies in Python development.\n\nRequirements:\n• Bachelor's degree in Computer Science, Software Engineering, or a related field.\n• Strong knowledge of Python programming language.\n• Familiarity with web frameworks such as Django or Flask.\n• Experience with version control systems, preferably Git.\n• Basic understanding of front-end technologies (HTML, CSS, JavaScript).\n• Good problem-solving and analytical skills.\n• Excellent communication and teamwork abilities.\n• Self-motivated and eager to learn.\n\nNice to have:\n• Experience with database systems such as MySQL, PostgreSQL, or MongoDB.\n• Knowledge of RESTful APIs and integration.\n• Familiarity with cloud platforms such as AWS or Azure.\n• Understanding of agile development methodologies.\n\nSpecial Benefits you will love:\n• Flexible vacation, paid holidays, and paid sick days\n• 401(k) with up to 2% employer match\n• Health, vision, and dental insurance\n\nSchedule: 8 hour shift, Monday to Friday , Time: Flexible, Job Type: Full-time\nEmployment Type: FULL_TIME",
		job_is_remote: true,
		job_posted_at_timestamp: 1687158000,
		job_posted_at_datetime_utc: "2023-06-19T07:00:00.000Z",
		job_city: "Houston",
		job_state: "TX",
		job_country: "US",
		job_latitude: 29.760427,
		job_longitude: -95.369804,
		job_benefits: [
			"dental_coverage",
			"retirement_savings",
			"paid_time_off",
			"health_insurance",
		],
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=I1mL8GW4cggAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-07-24T00:00:00.000Z",
		job_offer_expiration_timestamp: 1690156800,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: 70000,
		job_max_salary: 80000,
		job_salary_currency: "USD",
		job_salary_period: "YEAR",
		job_highlights: {
			Qualifications: [
				"Bachelor's degree in Computer Science, Software Engineering, or a related field",
				"Strong knowledge of Python programming language",
				"Familiarity with web frameworks such as Django or Flask",
				"Experience with version control systems, preferably Git",
				"Basic understanding of front-end technologies (HTML, CSS, JavaScript)",
				"Good problem-solving and analytical skills",
				"Excellent communication and teamwork abilities",
				"Self-motivated and eager to learn",
				"Experience with database systems such as MySQL, PostgreSQL, or MongoDB",
				"Knowledge of RESTful APIs and integration",
				"Familiarity with cloud platforms such as AWS or Azure",
				"Understanding of agile development methodologies",
			],
			Responsibilities: [
				"In this role, you will work closely with senior developers and other cross-functional teams to develop and maintain high-quality Python applications",
				"As a Junior Python Developer, you will have the opportunity to learn and grow your skills while contributing to exciting projects",
				"Collaborate with senior developers to design and develop Python applications",
				"Write clean, efficient, and maintainable code that follows best practices",
				"Participate in code reviews and provide constructive feedback",
				"Debug and fix issues in existing codebase",
				"Assist in testing and quality assurance processes",
				"Stay updated with the latest trends and technologies in Python development",
			],
			Benefits: [
				"REMOTE (US/Canada Residing people only, with work permit) Patterned Learning - Junior Python Developer-US/Canada , FULL-TIME, Salary $70K - $80K a year",
				"Flexible vacation, paid holidays, and paid sick days",
				"401(k) with up to 2% employer match",
				"Health, vision, and dental insurance",
				"Schedule: 8 hour shift, Monday to Friday , Time: Flexible, Job Type: Full-time",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"15-1132.00: Software Developers, Applications",
		],
	},
	{
		employer_name: "CyberCoders",
		employer_logo:
			"http://res.cloudinary.com/cybercoders/image/upload/v1386025236/CyberCoders%20is%20Acquired%20by%20On%20Assignment%20for%20%24105%20Million.png",
		employer_website: "http://www.cybercoders.com",
		employer_company_type: null,
		job_publisher: "LinkedIn",
		job_id: "tJ5p1qZ_HwIAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "REMOTE Python Engineer - Adtech Platform",
		job_apply_link:
			"https://www.linkedin.com/jobs/view/remote-python-engineer-adtech-platform-at-cybercoders-3643421229",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.5477,
		job_description:
			'If you are a Python with experience, please read on!\n\nBacked by the same people behind Comcast and NBCUniversal, there is confidence that our TV Advertising Platform is already impacting the way brands and apps use advertisements. Having recently secured our Series A Funding round, we are searching for another talented REMOTE Python Engineer to work alongside our team of EX Amazon, DirecTV and OpenX Engineers.\n\nAs a remote-first company it is important to be self-motivated, but collaboration is the key as we focus on a streamlined & impactful use of engineer time. The code you work on will have a direct & meaningful impact on the company product & customers.\n\nTop Reasons to Work with Us\n• 100% Remote-first Company!\n• Work alongside engineers from Amazon, DirecTV and OpenX\n• Recently received Series A Funding!\n\nWhat You Will Be Doing\n\nÏ Build efficient, high-performing features, APIs and systems that are standards-based and work across browsers and platforms.\n\nÏ Write efficient, clean, readable, fast, testable, documented, monitored code and systems.\n\nÏ Deliver new features to production.\n\nÏ Collaborate with Internal and External teams and other Software Engineers to deliver a compelling easy to use the product for the end-user / users.\n\nÏ Work closely with other engineers in a small, informal, remote team environment.\n\nÏ Ship code often in a fast-paced agile environment with continuous deployment.\n\nWork alongside and learn from talented engineers that have worked at Amazon, DirectTV and OpenX.\n\nWhat You Need for this Position\n\nÏ A great attitude.\n\nÏ A BS/MS in Computer Science or related on the job experience.\n\nÏ Strong problem-solving skills.\n\nÏ Production experience with Python.\n\nÏ Production experience with mySQL/RDS\n\nÏ Experience working with Django/Flask or similar python based web frameworks.\n\nÏ Experience writing integration and unit tests.\n\nÏ Strong problem-solving skills and ability to learn/adapt to new technologies.\n\nÏ Top-notch remote communication skills.\n\nÏ Passion for building reliable "done right the first time" web applications.\n\nÏ A self-directed team player.\n\nAbility to work under pressure and iterate quickly against rapidly updating plans.\n\nPlus But Not Required\n\nÏ Adtech Experience\n\nÏ Specific Domain Experience in CTV\n\nÏ Experience with AWS services.\n\nÏ Experience working within a microservice architecture.\n\nÏ Experience working with a customer facing reporting / analytics system in a production environment.\n\nÏ Experience working with snowflake.\n\nÏ Understanding of Linux and AWS technologies.\n\nWhat\'s In It for You\n• Vacation/PTO\n• Medical\n• Dental\n• Vision\n• 401k\n\nBenefits\n• Vacation/PTO\n• Medical\n• Dental\n• Vision\n• 401k\n• Bonus\n\nSo, if you are a REMOTE Python Engineer - Adtech Platform with experience, please apply today!\n\nEmail Your Resume In Word To\n\nLooking forward to receiving your resume through our website and going over the position with you. Clicking apply is the best way to apply, but you may also:\n\nDylan.Rogelstad@CyberCoders.com\n• Please do NOT change the email subject line in any way. You must keep the JobID: linkedin : DR5-1751140L636 -- in the email subject line for your application to be considered.***\n\nDylan Rogelstad - Lead Recruiter - CyberCoders\n\nApplicants must be authorized to work in the U.S.\n\nCyberCoders is proud to be an Equal Opportunity Employer\n\nAll qualified applicants will receive consideration for employment without regard to race, color, religion, sex, national origin, disability, protected veteran status, or any other characteristic protected by law.\n\nYour Right to Work – In compliance with federal law, all persons hired will be required to verify identity and eligibility to work in the United States and to complete the required employment eligibility verification document form upon hire.',
		job_is_remote: false,
		job_posted_at_timestamp: 1687582321,
		job_posted_at_datetime_utc: "2023-06-24T04:52:01.000Z",
		job_city: "Dallas",
		job_state: "TX",
		job_country: "US",
		job_latitude: 32.776665,
		job_longitude: -96.79699,
		job_benefits: ["paid_time_off", "retirement_savings"],
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=tJ5p1qZ_HwIAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-07-24T04:52:01.000Z",
		job_offer_expiration_timestamp: 1690174321,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: true,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: 140000,
		job_max_salary: 170000,
		job_salary_currency: "USD",
		job_salary_period: "YEAR",
		job_highlights: {
			Qualifications: [
				"Ï A great attitude",
				"Ï A BS/MS in Computer Science or related on the job experience",
				"Ï Production experience with Python",
				"Ï Production experience with mySQL/RDS",
				"Ï Experience working with Django/Flask or similar python based web frameworks",
				"Ï Experience writing integration and unit tests",
				"Ï Strong problem-solving skills and ability to learn/adapt to new technologies",
				"Ï Top-notch remote communication skills",
				'Ï Passion for building reliable "done right the first time" web applications',
				"Ï A self-directed team player",
				"Ability to work under pressure and iterate quickly against rapidly updating plans",
				"Ï Specific Domain Experience in CTV",
				"Ï Experience with AWS services",
				"Ï Experience working within a microservice architecture",
				"Ï Experience working with a customer facing reporting / analytics system in a production environment",
				"Ï Experience working with snowflake",
				"Ï Understanding of Linux and AWS technologies",
				"Applicants must be authorized to work in the U.S",
			],
			Responsibilities: [
				"Ï Build efficient, high-performing features, APIs and systems that are standards-based and work across browsers and platforms",
				"Ï Write efficient, clean, readable, fast, testable, documented, monitored code and systems",
				"Ï Deliver new features to production",
				"Ï Collaborate with Internal and External teams and other Software Engineers to deliver a compelling easy to use the product for the end-user / users",
				"Ï Work closely with other engineers in a small, informal, remote team environment",
			],
			Benefits: [
				"100% Remote-first Company!",
				"Work alongside engineers from Amazon, DirecTV and OpenX",
				"Recently received Series A Funding!",
				"Vacation/PTO",
				"Medical",
				"Dental",
				"Vision",
				"401k",
				"Bonus",
			],
		},
		job_job_title: "Engineer",
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
	},
	{
		employer_name: "SynergisticIT",
		employer_logo:
			"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
		employer_website: null,
		employer_company_type: null,
		job_publisher: "LinkedIn",
		job_id: "j-KZN-dmzF0AAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Entry Level Python Developer",
		job_apply_link:
			"https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3622574175",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.5613,
		job_description:
			"About Us\n\nSynergistic IT is a full-service staffing and placement firm servicing client in America for the past 12+ years. We are dedicated towards fulfilling the IT needs of our clients. From staffing to full implementation of projects we provide the highest quality IT Services. We Intend to deliver exceptional student outcome. We don't just help you secure a tech job but build a solid career in technology.\n\nJob Description\n• Should know how to work in large verities of libraries, frameworks, and modules\n• Duck typing, string, tuple and Lambda knowledge required\n• Django Frame work required\n• Worked on Django model, CBV, Django CRUD operation\n\nSkills Required-\n• Knowledge of Python web frameworks and event-driven programming in Python.\n• Basic understanding of front-end technologies.\n• High attention to detail.\n• Excellent communication and problem-solving skills.\n• Proficient understanding of code versioning tools\n• Know the classes of SCALA, Traits of SCALA, and Collection of SCALA\n\nEducation Requirement: -\n\nBachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering.\n\nBenefits\n• On Job Technical support\n• E- verified\n• Help to get H1b Employer.\n• Full time position\n\nCandidate who are missing the required skills, might be provided an option to enhance their skills, so that they can also apply for the role and can make a career in IT industry.\n\nIf you do respond via e-mail, please include a daytime phone number so that we can reach you. In considering candidates, time is of the essence, so please respond ASAP. Thank you",
		job_is_remote: false,
		job_posted_at_timestamp: 1683824834,
		job_posted_at_datetime_utc: "2023-05-11T17:07:14.000Z",
		job_city: "Dallas",
		job_state: "TX",
		job_country: "US",
		job_latitude: 32.776665,
		job_longitude: -96.79699,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=j-KZN-dmzF0AAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-07-05T17:07:14.000Z",
		job_offer_expiration_timestamp: 1688576834,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: false,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: true,
			degree_mentioned: true,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"Knowledge of Python web frameworks and event-driven programming in Python",
				"Basic understanding of front-end technologies",
				"High attention to detail",
				"Excellent communication and problem-solving skills",
				"Proficient understanding of code versioning tools",
				"Know the classes of SCALA, Traits of SCALA, and Collection of SCALA",
				"Bachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering",
			],
			Responsibilities: [
				"Should know how to work in large verities of libraries, frameworks, and modules",
				"Django Frame work required",
				"Worked on Django model, CBV, Django CRUD operation",
			],
			Benefits: ["On Job Technical support", "Full time position"],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
	},
	{
		employer_name: "Perceptive Analytics",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "ZipRecruiter",
		job_id: "BQYyjnVvf2AAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Python Developer - US",
		job_apply_link:
			"https://www.ziprecruiter.com/c/Perceptive-Analytics/Job/Python-Developer-US/-in-Houston,TX?jid=135670b6ee227feb",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.721,
		job_description:
			"What are we looking for?\n\nPerceptive Analytics is looking for a Python Developer. This role is based out of Houston - Texas Area, US, and will have direct interaction with our client.\n\nThis is an excellent opportunity for the candidate with 2-6 years of experience in Python, who is willing to do all it takes to deliver the best possible results. The position offers above industry standard compensation package and excellent growth prospects. The title will be customized to the candidate\\u2019s experience and capability.\n\nRequired Skills\n• 2 to 6 years of development experience in Python.\n• Knowledge of Django framework and Python libraries\n• Significant experience in client interaction.\n• Should good knowledge of OOP design and patterns .\n• Good analytical and communication skills.\n• Ability to work independently, but as part of a team toward common goals.\n• Workflow and data analysis skills.\n• Working proficiency in developmental toolsets.\n• Understanding of software skills such as business analysis, development, maintenance and software improvement\n• Knowledge on E-Commerce and Amazon market place will be a plus.\n\nAdditional Skills/Knowledge\n• Degree in, or comparable background/experience in, computer application or engineering a plus.\n• Documents - US work permit - H1B Visa or other work permit is mandatory.\n\nCover Letter Guidelines\n\nPlease ensure that you write about the following statement in your cover letter, in a separate paragraph. This will help us to gauge your understanding about the position and your overall thought process for this role. Overlooking this will lead to rejection of your resume.\n\n\\u201CThe joy of coding Python should be in seeing short, concise and readable classes.\\u201D\n\nAbout Perceptive Analytics:\n\nWe are a marketing analytics and business intelligence company specialized in sales and marketing analytics. Our business insights, dashboards, and visualizations help our clients make sense of their data quickly and take actions that increase revenues and substantially lift profits.\n\nIn the last 10 years, we've solved complex business problems for Fortune 200 companies like Morgan Stanley, JP Morgan Chase, American Century Investments and Melissa & Doug.\n\nWe are a fast growing data analytics company with sales offices in New York, Houston- Texas, Miami, Dallas, San Bruno, and head office at Hyderabad. We have formed long-term relationships with our clients and that's why 70% of our business comes from serving them.\n\nHere's why our clients love us:\n• Strong domain knowledge helps us understand their business challenges quickly.\n• Talented team uses analytical skills to uncover uncommon insights.\n• Dashboards and tools are extremely simple to use and quick to grasp.\n\nWe handpick talent after sorting through hundreds of resumes and hire people with good attitude and skills. We train our people continuously so that they continue to remain the best at what they do. Our workplace is fun, challenging.\n\nWhat do we offer?\n• Perceptive is known for its employee-friendly approach.\n• Friendly environment \\u2013 the opportunity to do great work and set high standards. We are open and straightforward. We encourage transparency and accountability. We manage ourselves and trust others.\n• Good pay.\n\nKEY HIGHLIGHTS:\n• Chosen as the \\u2018Top 10 Emerging Data Analytics Company of 2018\\u2019.\n• Serving Fortune 200 clients for the past decade.\n• Talented team with a good blend of data nerds and domain experts.\n\nKEY SERVICES:\n• E-COMMERCE: Campaign optimization, Conversion optimization & Cross-sell/upsell.\n• PHARMA: Supply chain analytics, Salesforce effectiveness, & Demand forecasting.\n• RETAIL: Market basket analysis, Markdown optimization, & Promotion effectiveness.",
		job_is_remote: false,
		job_posted_at_timestamp: 1687645800,
		job_posted_at_datetime_utc: "2023-06-24T22:30:00.000Z",
		job_city: "Houston",
		job_state: "TX",
		job_country: "US",
		job_latitude: 29.760427,
		job_longitude: -95.369804,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=BQYyjnVvf2AAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-07-25T00:00:00.000Z",
		job_offer_expiration_timestamp: 1690243200,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 24,
			experience_mentioned: true,
			experience_preferred: true,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"2 to 6 years of development experience in Python",
				"Knowledge of Django framework and Python libraries",
				"Significant experience in client interaction",
				"Should good knowledge of OOP design and patterns ",
				"Good analytical and communication skills",
				"Ability to work independently, but as part of a team toward common goals",
				"Workflow and data analysis skills",
				"Working proficiency in developmental toolsets",
				"Understanding of software skills such as business analysis, development, maintenance and software improvement",
				"Documents - US work permit - H1B Visa or other work permit is mandatory",
				"\\u201CThe joy of coding Python should be in seeing short, concise and readable classes.\\u201D",
				"Talented team uses analytical skills to uncover uncommon insights",
				"Friendly environment \\u2013 the opportunity to do great work and set high standards",
			],
			Responsibilities: [
				"This role is based out of Houston - Texas Area, US, and will have direct interaction with our client",
			],
			Benefits: [
				"The position offers above industry standard compensation package and excellent growth prospects",
				"Good pay",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"15-1132.00: Software Developers, Applications",
		],
	},
	{
		employer_name: "SynergisticIT",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "ZipRecruiter",
		job_id: "64rI85Q7b4wAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "PYTHON DEVELOPER(ENTRY LEVEL)",
		job_apply_link:
			"https://www.ziprecruiter.com/c/SynergisticIT/Job/PYTHON-DEVELOPER(ENTRY-LEVEL)/-in-Austin,TX?jid=95b95b82c4f3b4bd",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.6878,
		job_description:
			"Job Description\n\nSynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications and Background\n• Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\n• Mathematics or Statistics background\nSkills Required\n• 0 to 2 years of experience in Python development\n• Deep understanding of the software development life cycle\n• Knowledge of Linear Algebra, Statistics, and Mathematics concepts\n• Excellent written and verbal communication skills\n• Technically inquisitive, self-learner, team player, and highly motivated\n• Strong work ethics and creative problem-solving abilities\n\nPreferred Skills\n• Deep Learning\n• Data visualization\n• Scal\n• NLP\n• Django\nRoles and Responsibilities\ns an entry-level Python Developer, you need to perform the following duties:\n• Write server-side web application logic\n• Write scalable and effective codes in Python\n• Develop backend components to boost overall application's performance\n• Executing tests and fixing bugs in applications and software\n• Implement data protection and security solutions\n• Connect applications with third-party web services\n• Support frontend developers by integrating UI elements into Python applications\n\nBenefits\n• Competitive salary\n• Flexible work schedule & part-time off\n• E-verified\n• H1B Filing\n• No relocation\n• On job technical support\n• Skill Enhancement\n• Opportunity to work with Fortune 500 Companies\n\nWho can apply?\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.",
		job_is_remote: false,
		job_posted_at_timestamp: 1626998400,
		job_posted_at_datetime_utc: "2021-07-23T00:00:00.000Z",
		job_city: "Austin",
		job_state: "TX",
		job_country: "US",
		job_latitude: 30.267153,
		job_longitude: -97.74306,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=64rI85Q7b4wAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-07-24T00:00:00.000Z",
		job_offer_expiration_timestamp: 1690156800,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: 65000,
		job_max_salary: 140000,
		job_salary_currency: "USD",
		job_salary_period: "YEAR",
		job_highlights: {
			Qualifications: [
				"Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
				"Mathematics or Statistics background",
				"0 to 2 years of experience in Python development",
				"Deep understanding of the software development life cycle",
				"Knowledge of Linear Algebra, Statistics, and Mathematics concepts",
				"Excellent written and verbal communication skills",
				"Technically inquisitive, self-learner, team player, and highly motivated",
				"Strong work ethics and creative problem-solving abilities",
				"Support frontend developers by integrating UI elements into Python applications",
			],
			Responsibilities: [
				"Write server-side web application logic",
				"Write scalable and effective codes in Python",
				"Develop backend components to boost overall application's performance",
				"Executing tests and fixing bugs in applications and software",
				"Implement data protection and security solutions",
				"Connect applications with third-party web services",
			],
			Benefits: [
				"Competitive salary",
				"Flexible work schedule & part-time off",
				"No relocation",
				"On job technical support",
				"Opportunity to work with Fortune 500 Companies",
			],
		},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: [
			"15-1132.00: Software Developers, Applications",
		],
	},
	{
		employer_name: "Sigmaintel",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Learn4Good",
		job_id: "p_abgYsdqpIAAAAAAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Python Developer ONSITE",
		job_apply_link:
			"https://www.learn4good.com/jobs/dallas/texas/info_technology/2416947328/e/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.3892,
		job_description:
			"Strong Python, bash, Linux shell or similar Experience integrating with native AWS services (Code Pipeline, Code Commit, Code Build, Code Deploy, EC2, EKS, ECR, S3) Knowledge of networking, IAM, API and security assessment tools/methodologies. Familiar with container and orchestration. Familiar with IAM protocols such as SAML, SPML, XACML, SCIM, OpenID and OAuth. Understanding of the cyber threat landscape and methodologies to protect technology assets.\n\nAWS Certified Developer Associate or AWS Certified Solutions Architect Associate preferred. Excellent verbal and written communication skills Proficient in automation and deploying CI and CD tools and services (Jenkins Pipeline as Code, Git, Maven). Hands on experience building solutions with tools and services like AWS Cloud Formation, Terraform, or custom build orchestration tools leveraging SDKs or directly interacting with APIs Strong understanding of fundamental Application and Infrastructure Security concepts, including common types of attacks and exploitation techniques.\n\nSolid\n\nExperience with various application security tools (Example-ZAP, BURP, Tenable,Check Mark, Semmel, fortify, Sonatype, Kali, Web Inspect/App Scan, dependency check). Solid understanding of common web and systems application vulnerabilities.\n\nExperience integrating security tools into the Dev Ops environment (such as Zap or Burp)",
		job_is_remote: false,
		job_posted_at_timestamp: 1687478400,
		job_posted_at_datetime_utc: "2023-06-23T00:00:00.000Z",
		job_city: "Dallas",
		job_state: "TX",
		job_country: "US",
		job_latitude: 32.776665,
		job_longitude: -96.79699,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=p_abgYsdqpIAAAAAAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2023-12-22T00:00:00.000Z",
		job_offer_expiration_timestamp: 1703203200,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: false,
			professional_certification_mentioned: true,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {
			Qualifications: [
				"Strong Python, bash, Linux shell or similar Experience integrating with native AWS services (Code Pipeline, Code Commit, Code Build, Code Deploy, EC2, EKS, ECR, S3) Knowledge of networking, IAM, API and security assessment tools/methodologies",
				"Familiar with container and orchestration",
				"Familiar with IAM protocols such as SAML, SPML, XACML, SCIM, OpenID and OAuth",
				"Understanding of the cyber threat landscape and methodologies to protect technology assets",
				"Excellent verbal and written communication skills Proficient in automation and deploying CI and CD tools and services (Jenkins Pipeline as Code, Git, Maven)",
				"Hands on experience building solutions with tools and services like AWS Cloud Formation, Terraform, or custom build orchestration tools leveraging SDKs or directly interacting with APIs Strong understanding of fundamental Application and Infrastructure Security concepts, including common types of attacks and exploitation techniques",
				"Experience with various application security tools (Example-ZAP, BURP, Tenable,Check Mark, Semmel, fortify, Sonatype, Kali, Web Inspect/App Scan, dependency check)",
				"Solid understanding of common web and systems application vulnerabilities",
				"Experience integrating security tools into the Dev Ops environment (such as Zap or Burp)",
			],
		},
		job_job_title: "Onsite",
		job_posting_language: "en",
		job_onet_soc: "15113200",
		job_onet_job_zone: "4",
		job_occupational_categories: ["Java", "Python", "AWS", "Cyber Security"],
	},
];
